version: "3.2"

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16

services:
  webapp:
    container_name: flask_app
    restart: always
    build:
      context: ./application
      args:
        - hostname=172.16.1.3
    networks:
      my-network:
        ipv4_address: 172.16.1.2
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./application/src
        target: /src
    depends_on:
      - db

  db:
    container_name: mysql_db
    restart: always
    build:
      context: ./database
    networks:
      my-network:
        ipv4_address: 172.16.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./database/sql_scripts
        target: /docker-entrypoint-initdb.d
